### ISSUE TITLE
failed steps are no longer failing in IDEA 2020

### ISSUE THREAD

**Issue by rvowles** [dart-ogurets/OguretsIntellij#7]
##teamcity[testFailed timestamp = '2020-05-24T16:19:12.230' details = '/Users/richard/projects/featurehub/e2e//Users/richard/projects/featurehub/e2e/test/features/person_password.feature:25' message = 'ApiException 500:  (Inner exception: DioError [DioErrorType.RESPONSE]: Http status error [500])|n|n#0      DioMixin._dispatchRequest (package:dio/src/dio.dart:942:7)|n<asynchronous suspension>|n#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)|n#2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)|n#3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)|n#4      new Future.<anonymous closure> (dart:async/future.dart:174:37)|n#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)|n#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)|n#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)|n#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)|n' name = 'the administrator updates user "bruce@mailinator.com" to a new email "bruce2@mailinator.com" and new name "Bruke"' ]

**Comment by rvowles** [comment]
unable to reproduce
